services:
  - type: web
    name: lacak-lokasi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python lokasi_media_web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10